---
output: 
  stevetemplates::article:
    fig_caption: true
  keep_tex: yes
bibliography: olea.bib
biblio-style: apsr
title: "Nombre del artículo o informe"
author:
- name: Author Name
  affiliation: Affiliation
abstract: \textbf{Resumen } `r readLines('abstract.txt', encoding = 'UTF-8')`
keywords: "pandoc, r markdown, knitr"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: textwidth=170mm, textheight=235mm, footskip=12mm, voffset=10mm
#margin=1in
fontfamily: mathpazo
fontsize: 11pt
# spacing: double
endnote: no

header-includes: 
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \renewcommand{\headrulewidth}{0pt} %línea superior
- \renewcommand{\footrulewidth}{.8pt}%línea inferior
- \fancyhead[CO,CE]{This is fancy header}
- \fancyfoot[CO,CE]{And this is a fancy footer}
- \fancyfoot[LE,RO]{\thepage}
- \usepackage{multicol}
- \hoffset = -2mm
- \textwidth=170mm
- \twocolumn
- \setlength{\columnsep}{14mm}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE,
                      message=FALSE, warning=FALSE,
                      fig.path='figs/',
                      cache.path = '_cache/',
                      fig.process = function(x) {
                      x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
                      if (file.rename(x, x2)) x2 else x
                      })
```

```{r, echo=FALSE, include=FALSE}
# install.packages("openxlsx")
# install.packages("forecast")
# install.packages("/cloud/project/datos/LSTS_1.0.tar.gz", repos = NULL, type = "source")
# install.packages("corrplot")
# install.packages("plotrix")
# install.packages("car")
# install.packages("olsrr")
# install.packages("kableExtra")
library("kableExtra")
library("openxlsx")
library("forecast")
library("LSTS")
library("lmtest")
library("MASS")
library("corrplot")
library("car")
library("plotrix")
library("olsrr")
Data = read.xlsx('/cloud/project/datos/SMM.xlsx')
Data$BCU10 = Data$BCU10E
DF = na.omit(Data)
DF$TASA_HIP = NULL
DF$AÑO = NULL
DF$MES = NULL
DF$BCU10E = NULL
#head(DF)
attach(DF)
```


```{r child = 'chapter1.Rmd'}
```

```{r child = 'chapter2.Rmd'}
```

```{r child = 'chapter3.Rmd'}
```

```{r child = 'chapter4.Rmd'}
```

\section*{Referencias}
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\vspace*{-0.2in}
\noindent

