---
output:
  pdf_document: default
  html_document: default
bibliography: olea.bib
header-includes:
- \renewcommand\cite{\citep}
- \newcommand\shortcite{\citeyearpar}
- \newcommand\newcite{\citet}
---

\section*{Metodología}

En la literatura suele referirse a los prepagos mediante un indicador denominado
Conditional Prepayment Rate (${CPR}_t$) que surge de anualizar la tasa de prepago observada en el mes $t$, denominada Single Monthly Mortality Rate (${SMM}_t$):
$${SMM}_t = \frac{\sum^{n}_{i=1}{Prepago}_{it}}{\sum^{n}_{i=1}{({Saldo}_{it} - {Amortización}_{it})}}$$
donde $n$ representa el número de préstamos vigentes en el mes $t$, ${Prepago}_{it}$ el
monto pre-pagado (total o parcial) por cada crédito, ${Saldo}_{it}$ saldo de deuda al
inicio del mes y ${Amortización}_{it}$ la amortización programada dicho período. La anualización de la SMM se obtiene de la siguiente expresión:
$${CPR}_t = 1 - (1-{SMM}_t)^{12}$$
Las series históricas de prepagos, pueden ser explicadas también por factores exógenos como variables financieras y macro-económicas, pero la presencia de dependencia serial, hace recomendable la utilización de modelos
predictivos de series temporales, entre los más populares se encuentra el modelo \textbf{SARIMAX} (Seasonal Auto Regressive Integrated Moving Average eXogeneous
variables por sus siglas en inglés), que permite modelar series de tiempo no estacionarias, con estacionalidad, incorporando a su vez factores externos que pueden estar afectando el comportamiento de la serie.
La descripción matemática de un modelo SARIMAX$(p,d,q)\times {(P,D,Q)}_S$ es como sigue:
$$\varphi(B)\delta(B^S){(1-B)}^d{(1-B^S)}^D(Y_t - X_t\beta) = \theta(B)\vartheta(B^s)\varepsilon_t$$
Donde $Y_t$ es la serie a modelar, $B$ es un operador de rezago $BY_t = Y_{t-1}$, $X$ es una
matriz de regresores, $\beta$ es un vector de coeficientes, y $\varepsilon_t$ es una secuencia de errores no correlacionados. Los valores $d$ y $D$ corresponden al número de diferenciaciones necesarias para quitar efectos de tendencia y de estacionalidad, los cuales al considerar regresores son usualmente cero. Los valores $p$ y $q$ están asociados a la dependencia serial observada a la serie ajustada por los regresores. En el caso de detectar un patrón estacional $S$, se consideran además los valores $P$ y $Q$. Los polinomios asociados al modelo son:
\begin{eqnarray}
\varphi(B) = 1 + \varphi_1B + \dots + \varphi_pB^p\\
\delta(B^S) = 1 + \delta_1B^S + \dots + \delta_pB^{SP}\\
\theta(B) = 1 + \theta_1B + \dots + \theta_qB^q\\
\vartheta(B^s) = 1 + \vartheta_1B^S + \dots + \vartheta_QB^{SQ}
\nonumber
\end{eqnarray}
El ajuste de un modelo SARIMAX a los datos se realiza considerando varios aspectos relevantes. Por ejemplo, hay que especificar la estacionalidad $S$; la
diferenciación $d$, $D$; y los órdenes de rezago $p$, $P$, $q$, $Q$ para la serie de tiempo.
Usualmente esta especificación se lleva a cabo inspeccionando los gráficos de auto-correlaciones muestrales. Una vez determinados estos valores, se procede al cálculo de los estimadores para todos los coeficientes. Este paso se puede realizar en base a varios métodos de estimación, entre los que podemos mencionar el método de máxima verosimilitud o el método de momentos Yule-Walker. Una descripción detallada de estos y otros métodos de estimación puede encontrarse en los textos 
@Broc91 y @palma2016time.
