---
output: html_document
bibliography: mi_bib.bib  
---
# Metodología

En la literatura suele referirse a los prepagos mediante un indicador denominado
Conditional Prepayment Rate (${CPR}_t$) que surge de anualizar\footnote{Se realizan los cálculos asumiendo que la cantidad obtenida en el mes observado será constante para todos los meses del año.} la tasa de prepago observada en el mes $t$, denominada Single Monthly Mortality Rate (${SMM}_t$):
$${SMM}_t = \frac{\sum^{n}_{i=1}{Prepago}_{it}}{\sum^{n}_{i=1}{({Saldo}_{it} - {Amortización}_{it})}}$$
donde $n$ representa el número de préstamos vigentes en el mes $t$, ${Prepago}_{it}$ el
monto pre-pagado (total o parcial) por cada crédito, ${Saldo}_{it}$ el saldo de deuda al
inicio del mes y ${Amortización}_{it}$ la amortización (parte ya pagada de la deuda) programada para dicho período. La anualización de la SMM se obtiene de la siguiente expresión:
$${CPR}_t = 1 - (1-{SMM}_t)^{12}$$
Las series históricas de prepagos pueden ser explicadas también por factores exógenos, como variables financieras y macro-económicas. En el presente informe se ajustarán distintos modelos lineales para el $SMM$ mensual (elaborados por tanteo a partir del primero, en torno a las características que se detallarán), con el objetivo de comparar características que se detallarán más adelante.
A continuación, se definirán algunos conceptos clave para el correcto entendimiento del trabajo aquí presentado (En caso de que la lectora -o el lector- cuente con conocimientos de estadística, se aconseja avanzar directamente a la siguiente sección):

+ *Modelo lineal*: Sea una $Y$ una cantidad cuyo comportamiento aleatorio se desea estudiar (*variable respuesta*) con la finalidad o bien de predecir futuros valores o bien de estudiar su relación con otras ciertas cantidades $X_1, X_2, ..., X_n$ (éstas recibirán el nombre de *regresores*). Un modelo lineal en sus términos más simples consiste en proponer un cierto comportamiento de las variables en términos de distribuciones estadísticas (generalmente Normal) mediante establecer las siguientes condiciones:
$$Y = \beta_0 + \beta_1X_1 + \beta_2X_2 + \cdots +  + \beta_nX_n + \epsilon$$
$$\epsilon \sim N(0,1)$$
Donde los términos $\beta_k$ reciben el nombre de *coeficientes de regresión*, con $\beta_0$ siendo el *intercepto*, un término independiente que se interpreta como un coeficiente de intersección. 
Para más detalles sobre los fundamentos teóricos de los modelos lineales, se recomienda consultar el capítulo 3 del libro "Statistical Inference" por @tCAS90a.

+ *Significancia*: Definida para cada variable predictora considerada en un modelo, se dice que ésta es significativa si su *valor-p* es menor al nivel de significación previamente establecido (en el presente informe se considerará el valor $\alpha 0.05$ por es el más ampliamente utilizado). Una posible interpretación es que si una variable **no** es sifnificativa, entonces su efecto sobre la respuesta es trivial y no será necesario de considerar. Para efectos de comparación, se evaluará para cada modelo una métrica llamada N.S. (No Significativas) que contabiliza la proporción de variables consideradas en el modelo que según este criterio no significan un aporte. 

+ Calidad de ajuste: También llamada en la literatura como *bondad* de ajuste, es una medida de cuán bien funciona el modelo para predecir los valores de la respuesta. Se suelen usar algunas métricas estándar, en el presente informe se considerarán $R^2$, $R^2_{ajustado}$ y $AIC$.

+ Multi-colinealidad: En términos estadísticos se define como una medida de dependencia lineal entre variables predictoras. Para el lector no especializado se ofrece la siguiente interpretación: Si bien cada factor exógeno contribuye con información sobre el índice $SMM$, en caso de que algunos de ellos dependan de otros, habrá información redundante, lo cual dificultará el correcto funcionamiento del modelo. Para evaluar la multicolinealidad en un modelo se utiliza una métrica llamada $VIF$ (*variance inflation factor* por sus siglas en inglés) la cual al calcularse para cada factor, indicará que existe un problema de m.c. si su valor es mayor a $10$ (por convención).

## Referencias